### ISSUE TITLE
console logs

### ISSUE THREAD

**Issue by exomarty** [boomzillawtf/nodebb-plugin-upvote-notifications#2]
using plugin prints this on nodebb console 

UPVOTES
undefined
undefined

**Comment by boomzillawtf** [comment]
This was fixed in: https://github.com/boomzillawtf/nodebb-plugin-upvote-notifications/commit/2272378aed428dcfc524b8b9d45ac7cf3025879e

**Comment by boomzillawtf** [comment]
I updated npm to 0.1.3 removing that.
